language: node_js
node_js:
  - '8.9.3'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xclip
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
sudo: required
before_script:
  - npm i
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - npm test
after_script:
  - "sh -e /etc/init.d/xvfb stop"